### ISSUE TITLE
Compile all JSX schema needed for BCDB

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tf_cockpit#5]
We need to have an exhaustive list of all the JSX schema needed to populate the BCDB

**Comment by zaibon** [comment]
Here are all the schema we will use for the capacity parts:
```toml
@url = tfgrid.node.iface.1
name = (S)
addrs = (Liprange)
gateway = (Lipaddr)

@url = tfgrid.node.public_iface.1
master = (S)
type = "macvlan" (E)
ipv4 = (ipaddr)
ipv6 = (ipaddr)
gw4 = (ipaddr)
gw6 = (ipaddr)
version = (I)

@url = tfgrid.node.resource.1
cru = (I)
mru = (I)
hru = (I)
sru = (I)

@url = tfgrid.location.1
city = (S)
country = (S)
continent = (S)
latitude = (F)
longitude = (F)

@url = tfgrid.node.1
node_id* = (S)
farmer_id* = (S)
os_version* = (S)
parameters = (dict)
created = (T)
updated = (T)
uptime = (I)
address = (S)
location = (O) !tfgrid.location.1
total_resource = (O) !tfgrid.node.resource.1
used_resource = (O) !tfgrid.node.resource.1
reserved_resource = (O) !tfgrid.node.resource.1
ifaces = (LO) !tfgrid.node.iface.1
public_config = (O)!tfgrid.node.public_iface.1
exit_node = (B)
approved = false (B)

@url = tfgrid.farm.1
threebot_id* = (S) 
iyo_organization* = (S)
name* = (S)
wallet_addresses = (LS)
location = (O) !tfgrid.location.1
#email = (email)
vta = (S)
resource_price = (O) !tfgrid.node.resource.1

@url = tfgrid.node.proof.1
hardware = (dict)
hardware_hash = (S)
disks = (dict)
disks_hash = (S)
created = (T)
node_id* = (S) # link to the node
```

Here are the one for the provisioning part:
```toml
@url = tfgrid.network.1
net_id = (S)
prefix_zero = (iprange)
resources = (LO) !tfgrid.network.net_resource.1
exit_point = (O) !tfgrid.network.exit_point.1
allocation_nr = (I)
version = (I)

@url = tfgrid.network.node_id.1
node_id = (S)
farm_id = (S)
reachability_v4 = "PUBLIC,HIDDEN" (E)
reachability_v6 = "PUBLIC,HIDDEN" (E)

@url = tfgrid.network.net_resource.1
node_id = (O) !tfgrid.network.node_id.1
prefix = (iprange)
link_local = (iprange)
peers = (LO) ! tfgrid.network.peer.1
exit_point = (B)

@url = tfgrid.network.peer.1
prefix = (iprange)
connection = (O) !tfgrid.network.wireguard.1

@url = tfgrid.network.wireguard.1
ip = (ipaddr)
port = (ipport)
key = (S)
private_key = (S)

@url = tfgrid.network.ip4_conf.1
cidr = (iprange)
gateway = (ipaddr)
metric = (I)
iface = (S)
enable_nat = (B)

@url = tfgrid.network.ip6_conf.1
addr = (iprange)
gateway = (ipaddr)
metric = (I)
iface = (S)

@url = tfgrid.network.exit_point.1
#ip4_conf = (O) !tfgrid.network.ip4_conf.1
#ip4_dnat = (O) !tfgrid.network.ip4_dnat.1
ip6_conf = (O) !tfgrid.network.ip6_conf.1
ip6_allow = (Lipaddr)

@url = tfgrid.reservation.container.mount.1
volume_id = (S)
mountpoint = (S)

@url = tfgrid.reservation.container.1
flist = (S)
environment = (dict)
entrypoint = (S)
interactive = true (B)
volumes = (LO) !tfgrid.reservation.container.mount.1
network = (O) !tfgrid.reservation.network.1

@url = tfgrid.reservation.network.1
network_id = (S)

@url = tfgrid.reservation.volume.1
size = (I)
type = "HDD,SSD" (E)

@url = tfgrid.reservation.zdb.1
size = (I)
type = "seq,user" (E)
password = (S)
disk_type = "hdd,ssd" (E)
public = false (B)

@url = tfgrid.reservation.1
id = (S)
user = (S) #  Identification of the user requesting the reservation
type = "container,volume,network,zdb" (E)
data = (dict) 
signature = (S)
created = (T)
duration = (I)
```
